language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t marchartman/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true marchartman/docker-react npm run test -- --coverage

